# This is a Kubernetes job that builds PrusaSlicer
#
# Requirements:
# Kubernetes Cluster with ARM nodes, nodes should have at least >6Gb RAM.
# Ability to request a persistent volume (through a PVC) for build storage. 
#
# Lab Setup:
# 2x Radxa Rock5B 16GB running K3S with storage provided by Longhorn.
# 3x Raspberry Pi CM4 EMMC 4GB (used for management and smaller service tasks)
#
# Creating the namespace:
# $ kubectl create ns prusaslicer
#
# Launch job:
# $ kubectl apply -f job.yml -n prusaslicer
#
# Get job details:
# $ kubectl get job -n prusaslicer
#
# Getting the pods:
# $ kubectl get pods --selector=job-name=psbuild32 -n prusaslicer
# NAME            READY   STATUS    RESTARTS   AGE
# psbuild-s652n   1/1     Running   0          129m
#
# Following the log (psbuild64 to follow the aarch64 build, etc):
# $ kubectl logs -f jobs/psbuild32 -n prusaslicer
#
# Selecting the ARM64/aarch64 container:
# $ kubectl logs -f jobs/psbuild64 -n prusaslicer
#
# To extract the AppImages after the build is complete:
# $ kubectl exec psbuild-s652n -n prusaslicer -- bash -c "cd /build/PrusaSlicer-ARM.AppImage/;tar -zcf - *.AppImage" | tar -zxvf - -C ./
#
# Jobs persist after completing, removing:
# kubectl delete -f job.yml -n prusaslicer
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psbuild64-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psbuild32-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
# https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: psbuild32
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: psarm32
        image: ghcr.io/davidk/psarmhf-k8s:latest
        command: ["setarch","armv7l","./k8s-helper.sh","armhf"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        imagePullPolicy: Always
        resources:
          requests:
            memory: 6Gi
        volumeMounts:
          - name: psbuild32-data
            mountPath: /build
      restartPolicy: Never
      volumes:
        - name: psbuild32-data
          persistentVolumeClaim:
            claimName: psbuild32-longhorn-pvc
---
# https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: psbuild64
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: psarm64
        image: ghcr.io/davidk/psarm64-k8s:latest
        command: ["./k8s-helper.sh","aarch64"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: 6Gi
        volumeMounts:
          - name: psbuild64-data
            mountPath: /build
      restartPolicy: Never
      volumes:
        - name: psbuild64-data
          persistentVolumeClaim:
            claimName: psbuild64-longhorn-pvc

